Implementation of two-factor authentication and IVAs
ghga-de/archive-test-bed pull request #78
Opened 2024-04-10 11:29 UTC by dontseyit

2024-04-16 20:10 UTC, Cito requested changes
Very nice. Good to see that everything is working.

Made some suggestions below.

2024-04-16 20:10 UTC, Cito commented on features/33_work_packages.feature
>      And I am logged in as "Dr. John Doe"
```suggestion
    And I am logged in as "Dr. John Doe"
    And I am registered as "Dr. John Doe"
```

to show the proper order

2024-04-16 20:10 UTC, Cito commented on steps/test_30_user_registration.py
> +    assert user["title"] == title  # FIXME: title is None, but should be "Dr."
```suggestion
    assert user["title"] == title  # FIXME: title is None, but should be "Dr."
```

Is this comment still relevant?

2024-04-16 20:10 UTC, Cito commented on steps/test_31_user_verification.py
> +def sent_verification_code(verification_code: str, fixtures: JointFixture):
```suggestion
def send_verification_code(verification_code: str, fixtures: JointFixture):
```

2024-04-16 20:10 UTC, Cito commented on steps/test_31_user_verification.py
> +    iva_value = USER_IVAS.get(prop, None)
```suggestion
    iva_value = USER_IVAS.get(prop)
```

None is the default

2024-04-16 20:10 UTC, Cito commented on steps/test_40_delete_datasets.py
> +    headers = fixtures.auth.headers(session=session) if session else {}
Maybe make headers accept an empty session and return an empty dict in that case to simplify these constructs.

2024-04-17 10:58 UTC, dontseyit commented on fixtures/auth.py
> +            # Is there any scenario where we don't have an Auth Adapter?
With the current state of the test bed, without an auth adapter, some tests fail. So, if we really need to include this scenario, we should implement it properly (e.g., with 2FA operations, session states); in this case, we should address it in a separate PR.

2024-04-17 11:05 UTC, Cito commented on fixtures/auth.py
> +            # Is there any scenario where we don't have an Auth Adapter?
Yes, the test bed would not only have to emulate the token exchange, but also the TOTP functionality of the auth adapter, or skip these tests in that scenario.

Again, my feeling is that we should keep it simple and not support this scenario any longer, i.e. assume that we either test via API gateway (remote tests) or have the auth adapter directly accessible (local tests).

2024-04-17 11:11 UTC, dontseyit commented on fixtures/auth.py
> +            # Is there any scenario where we don't have an Auth Adapter?
I agree. I've removed the `use_auth_adapter` config and related code.

2024-04-17 11:27 UTC, Cito approved these changes
Thanks, looks good.

2024-04-17 11:33 UTC, merged